assignments/EnterpriseWebDevelopment/mytwitter/config/routes.rb
Mytwitter::Application.routes.draw do
  match '/rate' => 'rater#create', :as => 'rate'
	
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :media
  resources :genres
	

  resources :users       # NEW LINE
  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup',  to: 'users#new'

  resources :sessions, only: [:new, :create, :destroy]  # NEW LINE
  resources :microposts, only: [:create, :destroy] # NEW LINE
  resources :movie_reviews, only: [:create, :destroy, :index, :show, :edit, :update] # NEW LINE
  resources :relationships, :only => [:create, :destroy]

  match '/signin',  to: 'sessions#new'                  # NEW LINE
  match '/signout', to: 'sessions#destroy', via: :delete    # NEW LINE

end

assignments/EnterpriseWebDevelopment/mytwitter/app/controllers/movie_reviews_controller.rb
class MovieReviewsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user,   only: :destroy    # NEW LINE
  def show
    @movie_review = MovieReview.find(params[:id])
    @user = @movie_review.user
  end
  
  def create
    @movie_review = current_user.movie_reviews.build(params[:movie_review])
    if @movie_review.save
      flash[:success] = "Movie Review created!"
      redirect_to root_url
    else
      render 'static_pages/home' , :object => @movie_review
    end
  end
  
  def index
    if current_user.nil?
      @movie_reviews = MovieReview.find(:all)
    else
    @user = current_user
    @movie_reviews = @user.movie_reviews    # NEW LINE
    @movie_reviews_all =  MovieReview.find(:all)
    @microposts = current_user.microposts if signed_in?
    @micropost = current_user.microposts.build if signed_in?
    @movie_review = current_user.movie_reviews.build if signed_in?
    @genres = Genre.all if signed_in?
    @mediatypes = Medium.all if signed_in?
    end
  end
  
  # GET /genres/1/edit
  def edit
    @genres = Genre.all 
    @mediatypes = Medium.all 
    @movie_review = MovieReview.find(params[:id])
  end
  
  # PUT /genres/1
  # PUT /genres/1.json
  def update
    @movie_review = MovieReview.find(params[:id])

    respond_to do |format|
      if @movie_review.update_attributes(params[:movie_review])
        format.html { redirect_to @movie_review, notice: 'Movie was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end


  # UPDATED IMPLEMENTATION
  def destroy
    @movie_review.destroy
    redirect_to root_url
  end

  # NEW PRIVATE METHOD
  private

  def correct_user
    @movie_review = current_user.movie_reviews.find_by_id(params[:id])
    redirect_to root_url if @movie_review.nil?
  end
end

assignments/EnterpriseWebDevelopment/mytwitter/app/views/movie_reviews/_movie_review.html.erb
<% if !movie_review.reviewcontent.nil? %>
<div class="js-stream-item stream-item stream-item expanding-stream-item" data-item-id="288098988383666176" id="stream-item-tweet-288098988383666176" data-item-type="tweet">

	<div class="tweet original-tweet js-stream-tweet js-actionable-tweet js-profile-popup-actionable js-original-tweet

	has-cards

	"
	data-feedback-key="stream_status_288098988383666176"
	data-tweet-id="288098988383666176"

	data-item-id="288098988383666176"

	data-screen-name="waaf" data-name="WAAF" data-user-id="17789365"

	data-card-type="summary"

	data-expanded-footer=""

	>

		<i class="dogear"></i>
		<div class="content">

			<div class="stream-item-header">
				<small class="time"> <a href="/users/<%= movie_review.user.id %>" class="tweet-timestamp js-permalink js-nav" title="7:45 PM - 6 Jan 13" > <span class="_timestamp js-short-timestamp js-relative-timestamp" data-time="1357523126"
					data-long-form="true"><%= time_ago_in_words(movie_review.created_at) %> ago by <%= movie_review.user.name %>.</span></a> </small>
				<img alt="Movie" class="avatar js-action-profile-avatar" src="/assets/logo.jpg"> 
			</div>
			<u><%= movie_review.movietitle %></u>
			<p class="js-tweet-text">
				<%= movie_review.reviewtitle %>
			</p>

			<!-- NEW DELETE LINK -->
			<%= link_to 'read', movie_review_path(movie_review) %>
			<% if current_user?(movie_review.user) %>
			<%= link_to "delete", movie_review, method: :delete,
			data: { confirm: "You sure?" },
			title: movie_review.reviewcontent %>
			<%= link_to 'edit', edit_movie_review_path(movie_review) %>
			<% end %>
		</div>
	</div>
</div>
<% end %>

assignments/EnterpriseWebDevelopment/mytwitter/app/views/movie_reviews/_movie_review_detail.html.erb
<div class="content-inner">
	<p>
		<%= image_tag movie_review_detail.image %>
	<p>
		<span class="content"><%= movie_review_detail.reviewcontent %></span>
	<p>
</div>	
<div class="content-inner">
	<p>
		<span class="content"><strong>Genre : </strong><%= movie_review_detail.genre.name %></span>
	<p>
		<span class="content"><strong>Content Reviewed : </strong><%= Medium.find(movie_review_detail.media_id).name %></span>
		<p>
		<span class="content"><strong>Reviewed : </strong><%= movie_review_detail.revieweddate %></span>
	    <p>
		<span class="content"><strong>DVD Release : </strong><%= movie_review_detail.dvdreleasedate %></span>
		
		<% if movie_review_detail.theaterrelease? %>
	<p>
		<span class="content"><font color="blue">
				<p>
					In theaters everywhere today
				</p></font></span>
	<p>
		<% end %>
		<span class="timestamp"> Posted <%= time_ago_in_words(movie_review_detail.created_at) %> ago. </span>
<p>
		<% if signed_in? %>
		<div class="field">
			Average rating from all our users shown below! CLick to rate!
		</div><p>
		<% else %>
		<div class="field">
			Average rating from all our users shown below! You have to sign in to rate this movie!
		</div><p>
		<% end %>
		<div class="field">
			<strong>Rating : </strong><%= rating_for @movie_review, "starrating" %>
		</div>
</div>

assignments/EnterpriseWebDevelopment/mytwitter/app/views/movie_reviews/edit.html.erb
<h1>Editing movie</h1>

<%= render :partial => "shared/movie_review_form" ,:object => @movie_review, :html => { :id => "new_movie_review" } %>

assignments/EnterpriseWebDevelopment/mytwitter/app/views/movie_reviews/index.html.erb
<div id="page-container" class="wrapper wrapper-home white">
	<% if signed_in? %>
	<div class="dashboard">
		<div class="module mini-profile">
			<%= render 'shared/user_info' %>

			<%= render 'shared/stats' %>
			<% if !current_user.nil? %>
			<h2 class="js-timeline-title">All User Reviews</h2>
			<%= render @movie_reviews_all %>
			<% end %>
		</div>
	</div>
	<% else %>
	<div class="dashboard">
		<div class="module mini-profile">
			<div class="flex-module profile-summary js-profile-summary">

				<a href="/movie_reviews"
				class="account-summary account-summary-small js-nav"
				data-nav="profile">
				<div class="content">
					<div class="account-group js-mini-current-user" data-user-id="16120321" data-screen-name="mdreeling">
						<img class="avatar size32" src="assets/logo.jpg" alt="Mick">
						<b class="fullname">Movie Tweets!</b>
						<small class="metadata"> Your movie tweet resource</small>
						<small class="metadata"> (login or signup to post reviews!)</small>
					</div>
				</div> </a>
			</div>
			<div class="js-mini-profile-stats-container">
				<ul class="stats js-mini-profile-stats" data-user-id="16120321">
					<li>
						<a class="js-nav" href="/user" data-element-term="tweet_stats" data-nav='profile'> <strong><%= @movie_reviews.count %></strong> Reviews online</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<% end %>
	<div class="content-main" id="timeline">
		<div class="content-header">
			<div class="header-inner">

				<% if !current_user.nil? %>
				<h2 class="js-timeline-title">My Movie Reviews</h2>
				<% else %>
				<h2 class="js-timeline-title">All Users Movie Reviews</h2>
				<% end %>

			</div>
		</div>
		<div class="stream-container "
		data-max-id="288081372772458495" data-since-id="288098988383666176"

		>
			<div class="stream home-stream">
				<div class="stream-items" id="stream-items-id">
					<% if !current_user.nil? %>
					<% if current_user.movie_reviews.any? %>
					<%= render @movie_reviews %>
					<% end %>
					<% else %>
					<%= render @movie_reviews %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

assignments/EnterpriseWebDevelopment/mytwitter/app/views/movie_reviews/show.html.erb
<div id="page-container" class="wrapper wrapper-home white">
	<div class="dashboard">
		<div class="module mini-profile">
			<div class="flex-module profile-summary js-profile-summary">
			Reviewed by..
			</div>
			<%= render 'shared/user_info' %>
		</div>
	</div>

	<div class="content-main" id="timeline">
		<div class="content-header">
			<div class="header-inner">
				<h2 class="js-timeline-title"><%= @movie_review.movietitle %></h2>
			</div>
		</div>
		<div class="content-header">
			<div class="header-inner">
				<h4><%= @movie_review.reviewtitle %></h4>
			</div>
			
		<%= render :partial => "movie_review_detail" ,:object => @movie_review %>
		</div>
	</div>
</div>
</div>